/**
 * Generated by supabase/generate-types
 * Tip: Run `npx supabase gen types typescript --project-id horbbcnrcaeusuyuxvfqz > types/supabase.ts` para regenerar
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      rooms: {
        Row: {
          id: string
          name: string | null
          name_en: string | null
          name_es: string | null
          description: string | null
          description_en: string | null
          description_es: string | null
          price: number | null
          capacity: number | null
          size: string | null
          bed_type: string | null
          view_type: string | null
          amenities: Json | null
          images: Json | null
          is_active: boolean | null
          sort_order: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name?: string | null
          name_en?: string | null
          name_es?: string | null
          description?: string | null
          description_en?: string | null
          description_es?: string | null
          price?: number | null
          capacity?: number | null
          size?: string | null
          bed_type?: string | null
          view_type?: string | null
          amenities?: Json | null
          images?: Json | null
          is_active?: boolean | null
          sort_order?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string | null
          name_en?: string | null
          name_es?: string | null
          description?: string | null
          description_en?: string | null
          description_es?: string | null
          price?: number | null
          capacity?: number | null
          size?: string | null
          bed_type?: string | null
          view_type?: string | null
          amenities?: Json | null
          images?: Json | null
          is_active?: boolean | null
          sort_order?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      bookings: {
        Row: {
          id: string
          room_id: string | null
          booking_code: string
          guest_name: string
          guest_email: string
          guest_phone: string
          check_in: string
          check_out: string
          adults: number | null
          children: number | null
          total_price: number
          status: string | null
          payment_method: string | null
          payment_status: string | null
          special_requests: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          room_id?: string | null
          booking_code?: string
          guest_name?: string
          guest_email?: string
          guest_phone?: string
          check_in?: string
          check_out?: string
          adults?: number | null
          children?: number | null
          total_price?: number
          status?: string | null
          payment_method?: string | null
          payment_status?: string | null
          special_requests?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          room_id?: string | null
          booking_code?: string
          guest_name?: string
          guest_email?: string
          guest_phone?: string
          check_in?: string
          check_out?: string
          adults?: number | null
          children?: number | null
          total_price?: number
          status?: string | null
          payment_method?: string | null
          payment_status?: string | null
          special_requests?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bookings_room_id_fkey"
            columns: ["room_id"]
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          }
        ]
      }
      blocked_dates: {
        Row: {
          id: string
          room_id: string | null
          date: string
          reason: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          room_id?: string | null
          date?: string
          reason?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          room_id?: string | null
          date?: string
          reason?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "blocked_dates_room_id_fkey"
            columns: ["room_id"]
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, unknown>
        Relationships: Record<string, unknown>[]
      }
    }
    Functions: {
      [key: string]: {
        Name: string
        Schema: string
        Returns: string
      }
    }
    Storage: {
      [key: string]: {
        Table: {
          Row: Record<string, unknown>
          Insert: Record<string, unknown>
          Update: Record<string, unknown>
          Relationships: Record<string, unknown>[]
        }
        Bucket: string
        AllowedMimeTypes: string[]
      }
    }
  }
}

